{% set name = "stiff" %}
{% set version = "2.4.0" %}

package:
  name: astromatic-{{ name }}
  version: {{ version }}

source:
  url: https://github.com/astromatic/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ce64832c77846022c0be464982791e66442561fd0ca145d54068ef4d08dc2c81

build:
  skip: true  # [win]
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - libtiff
    - zlib

test:
  commands:
    - stiff -d

about:
  home: https://www.astromatic.net/software/stiff
  summary: |
    STIFF is a program that converts scientific FITS images to
    the more popular TIFF format for illustration purposes
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - drbixx
    - teake
